---

- name: install redis
  homebrew: name={{ item }} state=latest
  with_items:
    - redis

- name: check if redis is loaded
  shell: brew sevices list | grep redis | grep started
  changed_when: False
  register: redis_loaded_result

- name: launch redis
  shell: brew services start redis
  when: "'redis' not in redis_loaded_result.stdout"
